=== BrunoMCerqueira/FOC-Institute/Lenguaje de marcas y sistemas/Tarea Colaborativa/CLIENTES.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="clientes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="cliente" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="cliente" >
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="tipo">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="persona física"/>
              <xs:enumeration value="persona jurídica"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="años_de_relacion" type="xs:positiveInteger"/>
        <xs:element name="articulos_habituales">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="articulo_id">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="pedido_medio" type="xs:integer"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element> 
      </xs:sequence>
      <xs:attribute name="nif" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== BrunoMCerqueira/FOC-Institute/Lenguaje de marcas y sistemas/Tarea Colaborativa/CLIENTES.xml
<?xml version="1.0" encoding="UTF-8"?>
<clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CLIENTES.xsd">
  <cliente nif="91820114f">
    <nombre>Antonio Torres Yanes</nombre>
    <tipo>persona física</tipo>
    <años_de_relacion>10</años_de_relacion>
    <articulos_habituales>
      <articulo_id>561<pedido_medio>14</pedido_medio></articulo_id>
      <articulo_id>43<pedido_medio>10</pedido_medio></articulo_id>
    </articulos_habituales>
  </cliente>
  <cliente nif="5220194g">
    <nombre>Clinica Dental Sol</nombre>
    <tipo>persona jurídica</tipo>
    <años_de_relacion>4</años_de_relacion>
    <articulos_habituales>
      <articulo_id>415<pedido_medio>17</pedido_medio></articulo_id>
    </articulos_habituales>
  </cliente>
</clientes>
